#!/usr/bin/env bash
#localhost resolves to 127.0.0.2 & facebook.com resolves to 8.8.8.8

# Backup current /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Change localhost to 127.0.0.2
sudo sed -i '/^127.0.0.1 localhost$/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Change facebook.com to 8.8.8.8
sudo sed -i '/^8.8.8.8 facebook.com$/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Display updated /etc/hosts file
cat /etc/hosts
